kind: pipeline
name: default

clone:
  depth: 1

steps:
  - name: validate
    image: nikiai/geodesic-base:debian
    commands:
      - make init deps lint bash/fmt/check

  - name: publish
    image: banzaicloud/drone-kaniko
    settings:
      registry: gcr.io
      repo: niki-ai/geodesic
      tags:
        - ${DRONE_COMMIT_SHA}
        - latest
      cache: true
      json_key:
        from_secret: gcr_json_key

trigger:
  branch:
    - master
  event:
    - push