image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay

before_script:
  - apk add --update make curl bash git
  - echo $json_key | docker login https://asia.gcr.io -u _json_key --password-stdin

build-base:
  stage: build
  script:
    - make init
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - make base
  only:
    changes:
      - Dockerfile.base
      - packages.txt
    refs:
      - master

#build-master:
#  stage: build
#  script:
#    - make init
#    - make lint
#    - make packages/reinstall/shfmt
#    - make bash/fmt/check
#    - make docker/build
#    - make push
#  only:
#    refs:
#      - master
