#
# CI/CD configuration for https://travis-ci.org/cloudposse/geodesic/
#
sudo: required
addons:
  apt:
    packages:
    - git
    - make
    - curl
env:
  - DOCKER_IMAGE_NAME=nikiai/geodesic
services:
- docker
install:
- make init
- make travis/docker-login
- make packages/reinstall/shfmt
- make bash/fmt/check

script:
- make deps
- make lint
- make base
- make docker/build

after_success:
- make travis/docker-tag-and-push
