apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  name: {{getenv "KOPS_CLUSTER_NAME"}}
spec:
  additionalPolicies:
      master: |
        [
          {
            "Sid": "assumeClusterRole",
            "Action": [
              "sts:AssumeRole"
            ],
            "Effect": "Allow",
            "Resource": ["*"]
          }
        ]
      nodes: |
        [
          {
            "Sid": "assumeClusterRole",
            "Action": [
              "sts:AssumeRole"
            ],
            "Effect": "Allow",
            "Resource": ["*"]
          },
          {
            "Sid": "kopsK8sEC2NodeAmazonVPCPerms",
            "Effect": "Allow",
            "Action": [
              "ec2:CreateNetworkInterface",
              "ec2:AttachNetworkInterface",
              "ec2:DeleteNetworkInterface",
              "ec2:DetachNetworkInterface",
              "ec2:DescribeNetworkInterfaces",
              "ec2:DescribeInstances",
              "ec2:ModifyNetworkInterfaceAttribute",
              "ec2:AssignPrivateIpAddresses",
              "tag:TagResources"
            ],
            "Resource": [
              "*"
            ]
          }
        ]
  api:
    loadBalancer:
      type: Public
  authorization:
    rbac: {}
  authentication:
    aws: {}
  iam:
    allowContainerRegistry: true
    legacy: false
  channel: stable
  cloudLabels:
    Cluster: {{getenv "KOPS_CLUSTER_NAME"}}
    kubernetes.io/cluster/{{getenv "KOPS_CLUSTER_NAME"}}: owned
  cloudProvider: aws
  kubeDNS:
    provider: CoreDNS
  configBase: {{getenv "KOPS_STATE_STORE" }}/{{getenv "KOPS_CLUSTER_NAME"}}
  {{if getenv "KOPS_DNS_ZONE" }}
  dnsZone: {{getenv "KOPS_DNS_ZONE"}}
  {{else}}
  dnsZone: {{getenv "KOPS_CLUSTER_NAME" | regexp.Replace "^[^.]+\\." ""}}
  {{end}}
  etcdClusters:
  - etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-{{ index (getenv "KOPS_AVAILABILITY_ZONES" | strings.Split ",") 0 }}
      name: {{ index (getenv "KOPS_AVAILABILITY_ZONES" | strings.Split ",") 0  | regexp.Replace "^.*[0-9]" ""}}
    name: main
  - etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-{{ index (getenv "KOPS_AVAILABILITY_ZONES" | strings.Split ",") 0 }}
      name: {{ index (getenv "KOPS_AVAILABILITY_ZONES" | strings.Split ",") 0  | regexp.Replace "^.*[0-9]" ""}}
    name: events
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: {{getenv "KUBERNETES_VERSION"}}
  masterPublicName: api.{{getenv "KOPS_CLUSTER_NAME"}}
  networkCIDR: {{getenv "TF_VAR_cidr_block"}}
  networkID: {{getenv "VPC_ID"}}
  networking:
    amazonvpc: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshKeyName: {{getenv "TF_VAR_namespace"}}-{{getenv "TF_VAR_stage"}}-kops-{{getenv "TF_VAR_kops_region"}}
  sshAccess:
  - 0.0.0.0/0
  subnets:
  {{- range $index, $value := (getenv "KOPS_AVAILABILITY_ZONES" | strings.Split ",") }}
  {{- $privateSubnets := getenv "KOPS_PRIVATE_SUBNETS" }}
  {{- $subnet := strings.Split "," $privateSubnets }}
  - cidr: {{ index $subnet $index }}
    name: {{ $value }}
    type: Private
    zone: {{ $value }}
  {{- end }}
  {{- range $index, $value := (getenv "KOPS_AVAILABILITY_ZONES" | strings.Split ",") }}
  {{- $utilitySubnets := getenv "KOPS_UTILITY_SUBNETS" }}
  {{- $subnet := strings.Split "," $utilitySubnets }}
  - cidr: {{ index $subnet $index }}
    name: utility-{{ $value }}
    type: Utility
    zone: {{ $value }}
  {{- end }}
  topology:
    bastion:
      bastionPublicName: {{ getenv "KOPS_BASTION_PUBLIC_NAME"}}.{{getenv "KOPS_CLUSTER_NAME"}}
    dns:
      type: Public
    masters: private
    nodes: private

---
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: {{getenv "KOPS_CLUSTER_NAME"}}
  name: bastions
spec:
  image: {{getenv "KOPS_BASE_IMAGE"}}
  machineType: {{getenv "BASTION_MACHINE_TYPE"}}
  maxSize: 1
  minSize: 1
  role: Bastion
  subnets:
  {{- range (getenv "KOPS_AVAILABILITY_ZONES" | strings.Split ",") }}
  - utility-{{.}}
  {{- end }}

---
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: {{getenv "KOPS_CLUSTER_NAME"}}
  name: master-{{ index (getenv "KOPS_AVAILABILITY_ZONES" | strings.Split ",") 0 }}
spec:
  associatePublicIp: false
  image: {{getenv "KOPS_BASE_IMAGE"}}
  machineType: {{getenv "MASTER_MACHINE_TYPE"}}
  maxSize: 1
  minSize: 1
  role: Master
  subnets:
  - {{ index (getenv "KOPS_AVAILABILITY_ZONES" | strings.Split ",") 0 }}

---
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: {{getenv "KOPS_CLUSTER_NAME"}}
  name: memory
spec:
  nodeLabels:
    kubernetes.io/type: memory
  associatePublicIp: false
  image: {{getenv "KOPS_BASE_IMAGE"}}
  machineType: {{getenv "MEMORY_NODE_MACHINE_TYPE"}}
  maxSize: {{getenv "MEMORY_NODE_MAX_SIZE"}}
  minSize: {{getenv "MEMORY_NODE_MIN_SIZE"}}
  maxPrice: "0.052"
  role: Node
  subnets:
  {{- range (getenv "KOPS_AVAILABILITY_ZONES" | strings.Split ",") }}
  - {{.}}
  {{- end }}

---
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: {{getenv "KOPS_CLUSTER_NAME"}}
  name: compute
spec:
  nodeLabels:
    kubernetes.io/type: compute
  associatePublicIp: false
  image: {{getenv "KOPS_BASE_IMAGE"}}
  machineType: {{getenv "COMPUTE_NODE_MACHINE_TYPE"}}
  maxSize: {{getenv "COMPUTE_NODE_MAX_SIZE"}}
  minSize: {{getenv "COMPUTE_NODE_MIN_SIZE"}}
  maxPrice: "0.052"
  role: Node
  subnets:
  {{- range (getenv "KOPS_AVAILABILITY_ZONES" | strings.Split ",") }}
  - {{.}}
  {{- end }}
