# Setup some handy aliases
alias kube-system='kubectl --namespace=kube-system'
alias default='kubectl --namespace=default'
alias telnet='busybox-extras telnet'
alias k='kubectl'
alias kaf='k apply -f'
alias kccc='k config current-context'
alias kcdc='k config delete-context'
alias kcsc='k config set-context'
alias kcuc='k config use-context'
alias kdd='k describe deployment'
alias kdeld='k delete deployment'
alias kdelp='k delete pods'
alias kdels='k delete svc'
alias kdelsec='k delete secret'
alias kdp='k describe pods'
alias kds='k describe svc'
alias kdsec='k describe secret'
alias ked='k edit deployment'
alias kep='k edit pods'
alias kes='k edit svc'
alias keti='k exec -ti'
alias kg='k get'
alias kgd='k get deployment'
alias kgp='k get pods'
alias kgrs='k get rs'
alias kgs='k get svc'
alias kgsec='k get secret'
alias kl='k logs'
alias klf='k logs -f'
alias kp='k proxy --address 0.0.0.0 --accept-hosts '"'"'.*'"'"' --port=$KUBERNETES_API_PORT'
alias krh='k rollout history'
alias krsd='k rollout status deployment'
alias kru='k rollout undo'
alias ksd='k scale deployment'
